import asyncio
import json
import os
from typing import Any, Dict, List, Optional, Tuple

# Simple LLM adapter that supports 'mock' and 'openai' providers.
# Select provider with env var LLM_PROVIDER (mock|openai). If not set and
# CHATGPT_API_KEY is present, default to openai.

LLM_PROVIDER = os.getenv("LLM_PROVIDER", os.getenv("USE_MOCK_LLM", "mock"))
CHATGPT_API_KEY = os.getenv("CHATGPT_API_KEY")

try:
    import openai
except Exception:
    openai = None
try:
    # Standard library will be used for Gemini HTTP calls; no extra dependency required.
    import urllib.request as _urllib_request
    import urllib.error as _urllib_error
except Exception:
    _urllib_request = None
    _urllib_error = None

# Gemini configuration
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "models/text-bison-1")
GEMINI_ENDPOINT = os.getenv("GEMINI_ENDPOINT", "https://generativelanguage.googleapis.com/v1")


def _mock_response(prompt: str) -> str:
    """Return a deterministic mock response useful for tests."""
    # If the prompt looks like a JSON generation request, return a minimal JSON
    if "Reply format" in prompt or "Reply format:" in prompt or "Directly return the final JSON" in prompt:
        # A safe default: an empty JSON object
        return "{}"
    # For summary requests, return a short fixed string
    if "generate a description" in prompt or "generate a one-sentence description" in prompt:
        return "A short description generated by mock LLM."
    # Otherwise, echo back a truncated prompt
    return prompt.strip()[:200]


def ChatGPT_API_with_finish_reason(
    model: str,
    prompt: str,
    api_key: Optional[str] = CHATGPT_API_KEY,
    chat_history: Optional[List[Dict[str, str]]] = None,
    max_retries: int = 1,
) -> Tuple[str, str]:
    if LLM_PROVIDER == "mock":
        return _mock_response(prompt), "finished"

    if LLM_PROVIDER == "openai":
        if openai is None:
            raise RuntimeError("openai package not installed")
        client = openai.OpenAI(api_key=api_key)
        response = client.chat.completions.create(model=model, messages=chat_history or [{"role": "user", "content": prompt}], temperature=0)
        choice = response.choices[0]
        finish_reason = getattr(choice, "finish_reason", None)
        content = getattr(choice.message, "content", choice.text if hasattr(choice, "text") else "")
        if finish_reason == "length":
            return content, "max_output_reached"
        return content, "finished"

    if LLM_PROVIDER == "gemini":
        # Use Google Generative Language API via REST. Requires GEMINI_API_KEY env var.
        if GEMINI_API_KEY is None:
            raise RuntimeError("GEMINI_API_KEY is not set for Gemini provider")
        if _urllib_request is None:
            raise RuntimeError("urllib not available for Gemini HTTP calls")

        url = f"{GEMINI_ENDPOINT}/models/{model}:generateText" if model else f"{GEMINI_ENDPOINT}/{GEMINI_MODEL}:generateText"
        # Build request payload
        body = {"prompt": {"text": prompt}, "temperature": 0}
        data = json.dumps(body).encode("utf-8")
        req = _urllib_request.Request(url, data=data, headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {GEMINI_API_KEY}"
        })
        try:
            with _urllib_request.urlopen(req, timeout=30) as resp:
                resp_data = resp.read().decode("utf-8")
                j = json.loads(resp_data)
                # Response typically contains 'candidates' with 'output'
                candidates = j.get("candidates") or j.get("outputs") or []
                if candidates:
                    # Try multiple candidate shapes
                    first = candidates[0]
                    content = first.get("output") or first.get("text") or first.get("content") or ""
                    return content, "finished"
                # Fallback to top-level 'output' or 'text'
                if "output" in j:
                    return j["output"], "finished"
                if "text" in j:
                    return j["text"], "finished"
                return json.dumps(j), "finished"
        except Exception as e:
            raise RuntimeError(f"Gemini API request failed: {e}")

    raise RuntimeError(f"Unsupported LLM_PROVIDER: {LLM_PROVIDER}")


def ChatGPT_API(
    model: str,
    prompt: str,
    api_key: Optional[str] = CHATGPT_API_KEY,
    chat_history: Optional[List[Dict[str, str]]] = None,
    max_retries: int = 1,
) -> str:
    content, _ = ChatGPT_API_with_finish_reason(model=model, prompt=prompt, api_key=api_key, chat_history=chat_history, max_retries=max_retries)
    return content


async def ChatGPT_API_async(
    model: str,
    prompt: str,
    api_key: Optional[str] = CHATGPT_API_KEY,
    chat_history: Optional[List[Dict[str, str]]] = None,
    max_retries: int = 1,
) -> str:
    if LLM_PROVIDER == "mock":
        return _mock_response(prompt)
    if LLM_PROVIDER == "openai":
        if openai is None:
            raise RuntimeError("openai package not installed")
        async with openai.AsyncOpenAI(api_key=api_key) as client:
            response = await client.chat.completions.create(model=model, messages=chat_history or [{"role": "user", "content": prompt}], temperature=0)
            return getattr(response.choices[0].message, "content", "")
    raise RuntimeError(f"Unsupported LLM_PROVIDER: {LLM_PROVIDER}")
